spring:
  application:
    name: ${APPLICATION_NAME}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: ${PORT:8081}

face:
  service:
    url: ${FACE_SERVICE_URL}

storage:
  location: uploads

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET_KEY}

photo-recognition:
  url: ${PHOTO_RECOGNITION_API_URL}